print(3 + 4)
print(3 - 4)
print(3 * 4)
print(10 % 2)
print(10 / 3)
print(10 // 3)
print(10 ** 3)
print()
print("Hola" + "Python")
print("Hola"*2)
print()
print(True+False)
print(True+True)
print(False+False)
print("Hola" > "Hela")
print(3 > 4 and "Hola" > "Python")
print(3 > 4 or "Hola" > "Python")
print(3 > 4 or ("Hola" > "Python" and 4 ==4))
print(not(3 > 4 or "Hola" > "Python"))

